### ISSUE TITLE
Error on adding contiguous keys

### ISSUE THREAD

**Issue by jmagan** [aiken-lang/sparse-merkle-tree#1]
Hi! 

I was playing with this repository and I found something weird. I did a simple test adding 4 contiguous keys, like this:

```rust
#[test]
fn contiguous_add_keys_test() {
    let mut tree = SMT::default();
    //println!("This is the default tree \n {:?}", tree.store().branches_map());

    let mut bytes_list = [
        hex!("0000000000000000000000000000000000000000000000000000000000000001"),
        hex!("0000000000000000000000000000000000000000000000000000000000000002"),
        hex!("0000000000000000000000000000000000000000000000000000000000000003"),
        hex!("0000000000000000000000000000000000000000000000000000000000000004"),
    ];

    bytes_list.sort_unstable();

    for bytea in &bytes_list {
        let key: H256 = { (*bytea).into() };

        let value: H256 = { (*bytea).into() };
        tree.update(key, value, true).expect("update");
    }
    println!("This is after addition tree \n {:#?}", tree.store().branches_map());
}
```

I've analyzed the problem and I found that this if statement fails because `i - ((key.height + 1) % 8)`is -1.

https://github.com/aiken-lang/sparse-merkle-tree/blob/b7180ed2abe11ab0b750429aee182a14bf2e74fe/src/tree.rs#L75-L82

I was trying to make sense of this code but I don't know why we use this special case in the if statement. If it's correct, could you explain me why do we need it?

Thanks

**Comment by MicroProofs** [comment]
I'll give your test case a try

**Comment by MicroProofs** [comment]
Latest commits fix this test. Working on performance, but this should unblock any usage.
